version = 1

[merge]
delete_branch_on_merge = true
notify_on_conflict = false
require_automerge_label = false

[merge.automerge_dependencies]
versions = ["minor", "patch"]
usernames = ["dependabot"]

[approve]
auto_approve_usernames = ["dependabot"]
