name: Testing
on:
  push:
  pull_request:

jobs:
  testing:
    name: Unit tests
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [ 14.x ]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          path: ladybug-frontend

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'
          cache-dependency-path: '**/package-lock.json'

      - name: Install packages
        run: npm ci
        working-directory: ladybug-frontend

      - name: Build project
        run: npm run build

      - name: Run linter
        run: npm run lint

      - name: Run unit tests
        run: npm run test-headless
        continue-on-error: false

      - name: Checkout frank-runner
        uses: actions/checkout@v2
        with:
          repository: ibissource/frank-runner
          path: frank-runner

      - name: Checkout ibis-ladybug
        uses: actions/checkout@v2
        with:
          repository: ibissource/ibis-ladybug
          path: ibis-ladybug

      - name: Checkout ibis-ladybug-test-webapp
        uses: actions/checkout@v2
        with:
          repository: ibissource/ibis-ladybug-test-webapp
          path: ibis-ladybug-test-webapp

      - name: List all files
        run: ls