name: Testing
on:
  push:
  pull_request:

jobs:
  testing:
    name: Unit tests
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [ 14.x ]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          path: ladybug-frontend

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'
          cache-dependency-path: '**/package-lock.json'

      - name: Install packages
        run: npm ci
        working-directory: ladybug-frontend

      - name: Build project
        run: npm run build
        working-directory: ladybug-frontend

      - name: Run linter
        run: npm run lint
        working-directory: ladybug-frontend

      - name: Run unit tests
        run: npm run test-headless
        working-directory: ladybug-frontend
        continue-on-error: false

      - name: Checkout frank-runner
        uses: actions/checkout@v2
        with:
          repository: ibissource/frank-runner
          path: frank-runner
      - name: Set port where ibis-ladybug-test-webapp is served
        run: echo "tomcat.connector.port=8080" > frank-doc/build.properties

      - name: Checkout ibis-ladybug
        uses: actions/checkout@v2
        with:
          repository: ibissource/ibis-ladybug
          path: ibis-ladybug

      - name: Checkout ibis-ladybug-test-webapp
        uses: actions/checkout@v2
        with:
          repository: ibissource/ibis-ladybug-test-webapp
          path: ibis-ladybug-test-webapp

      - name: Cache Frank!Runner dependencies
        uses: actions/cache@v2
        with:
          path: |
            frank-runner/build
            frank-runner/download
          key: ${{ runner.os }}-frank-runner
          restore-keys: |
            ${{ runner.os }}-frank-runner
      - name: Run cypress using the Frank!Runner
        uses: cypress-io/github-action@v2.9.7
        with:
          working-directory: ladybug-frontend
          start: |
            run frank-runner/specials/ibis-ladybug/restart.sh
            run ng serve
          wait-on: |
            "http://localhost:8080"
            "http://localhost:4200"
          wait-on-timeout: 240
      - name: Store (logging) information as artifacts
        uses: actions/upload-artifact@v2
        with:
          name: logs
          path: |
            frank-runner/build/apache-tomcat-9.0.50/logs/catalina.out
            ladybug-frontend/cypress/screenshots/
